# Generated by Django 2.2.6 on 2019-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=70)),
                ('numero', models.IntegerField(verbose_name='número')),
                ('complemento', models.CharField(max_length=70)),
                ('bairro', models.CharField(max_length=70)),
                ('cidade', models.CharField(max_length=20)),
                ('uf', models.CharField(choices=[('PI', 'PI'), ('PE', 'PE')], max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'ordering': ('bairro', 'cidade', 'uf'),
            },
        ),
        migrations.CreateModel(
            name='ItemTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ('nome',),
            },
        ),
    ]
