# Generated by Django 2.2.6 on 2019-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor do aluguel')),
                ('cor_toalha', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ('nome', 'valor_aluguel'),
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nome',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='UF'),
        ),
    ]
