# Generated by Django 2.2.6 on 2019-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191020_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='item',
            field=models.ManyToManyField(to='core.ItemTema'),
        ),
    ]
