# Generated by Django 2.2.5 on 2019-10-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tema_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_festa', models.DateField(verbose_name='Data da festa')),
                ('hora_inicio', models.DateField(verbose_name='Horário do ínicio')),
                ('hora_termino', models.DateField(verbose_name='Horário do término')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tema')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Alugueis',
            },
        ),
    ]
