# Generated by Django 2.2.6 on 2019-10-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191026_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
    ]
